/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false` (hash: f5b993280aa9dea314a8d9f70775390f)
interface __BaseEnv_Env {
	LAMBDA_FUNCTION_URL: "https://e3xuzho3aahlliid63ecfaslvy0afgce.lambda-url.ap-southeast-1.on.aws/";
	AWS_REGION: "ap-southeast-1";
	CORS_ALLOWED_ORIGINS: "https://dich.vn-converter.org,http://localhost:5173";
	AWS_ACCESS_KEY_ID: string;
	AWS_SECRET_ACCESS_KEY: string;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/index");
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "LAMBDA_FUNCTION_URL" | "AWS_REGION" | "CORS_ALLOWED_ORIGINS" | "AWS_ACCESS_KEY_ID" | "AWS_SECRET_ACCESS_KEY">> {}
}
