/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false` (hash: 3c1f2bfed7aa3ce1164f2b0b74305d7a)
interface __BaseEnv_Env {
	UPSTREAM_BASE_URL: "http://192.0.2.10/v1";
	CORS_ALLOWED_ORIGINS: "https://dich.vn-converter.org,http://localhost:5173";
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/index");
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "UPSTREAM_BASE_URL" | "CORS_ALLOWED_ORIGINS">> {}
}
